### ISSUE TITLE
Maybe add extensions/libraries required by Wordpress to composer file

### ISSUE THREAD

**Issue by tomasruud** [roots/wordpress#12]
I'm not certain about what extensions and libraries Wordpress actually requires to run, and which one of those that are considered "default" in php. But I think it would be a nice addition to indicate what Wordpress actually requires when adding it to a project.

I've recently tried setting up a wp+composer project with docker, and ran into a problem where some of the extensions were not enabled by default in the php docker image. I guess I would have figured out the problem quicker if I knew that some extensions were missing.

**Comment by tomasruud** [comment]
@LeoColomb oh wow, I haven't seen that. Is this live yet?

**Comment by LeoColomb** [comment]
@tomasruud I don't think so... Honestly, even as a contributor, the pace of development and releasing of the Roots team is difficult to follow, since we do not have access to project discussions, so I don't know what is the status of the wp-packager. 😉

**Comment by austinpray** [comment]
@LeoColomb Regarding project discussions about roots/wordpress-packager: literally everything is in issues and on GH. There hasn't been any discussion elsewhere. I can add a roadmap to https://github.com/roots/wordpress-packager/projects to make it easer to follow/easy to see what the next step is. It's definitely been slow going because I don't have a budget to work on roots/wordpress-packager and nobody has really been asking for it. I can get a proposal rolling though. roots/wordpress-packager is definitely gonna be easier to maintain/more well-tested than what is in this repo currently.

@tangrufus In the meantime maybe we backport this feature to this repo just like we were gonna do with https://github.com/roots/wordpress/pull/9 ?

**Comment by TangRufus** [comment]
Main challenge is to find out required extensions/libraries for different WordPress versions.

http://displaywp.com/version/52/ is the closest thing I could find. However, it doesn't include extension info.

Related: 
- https://github.com/ItinerisLtd/wordpress-packager/issues/15
- https://github.com/roots/wordpress-packager/issues/40

---

> It's definitely been slow going because I don't have a budget to work on roots/wordpress-packager and nobody has really been asking for it.

Similar situation to me. I started [ItinerisLtd/wordpress-packager](https://github.com/ItinerisLtd/wordpress-packager) because I wanted to make a composer plugin to perform [signature verification](https://make.wordpress.org/core/2019/05/17/security-in-5-2/) during `composer install`. However, it seems [those signatures never been published](https://make.wordpress.org/core/2019/05/17/security-in-5-2/#comment-35879). Probably, I won't spend much time on this project and wordpress-packager until wp.org actually set up signature verification.

**Comment by johnbillion** [comment]
Related:

* https://core.trac.wordpress.org/ticket/48086
* https://github.com/johnbillion/ext
* https://github.com/johnbillion/ext/issues/7

**Comment by austinpray** [comment]
wow they finally added the list! https://github.com/WordPress/hosting-handbook/blob/master/server-environment.md#php-extensions
