### ISSUE TITLE
Automatically updated?

### ISSUE THREAD

**Issue by haswalt** [roots/wordpress#2]
Appears to be behind and releases look manual?

How do I easily update to latest wordpress version (5.1.0 at time of writing)

**Comment by austinpray** [comment]
The [GitHub releases](https://help.github.com/en/articles/creating-releases) are manual. The tagging and pushing to composer is completely automated. Purely because the auto update script doesn't make a call to github.

The GitHub releases are just for aesthetic purposes 
![image](https://user-images.githubusercontent.com/2192970/53212528-e3be8e80-360a-11e9-871d-93ce195c8eda.png)


https://travis-ci.com/roots/wordpress/builds is a history of the automated builds. 5.1 just landed.
